### ISSUE TITLE
Code release time

### ISSUE THREAD

**Issue by ellen19967** [ucla-mobility/V2V4Real#1]
Thanks for the great work! When will the code and dataset be released?

**Comment by DerrickXuNu** [comment]
I have already release the code base for cooperative detection. For dataset, I am uploading it right now, and it should be seen in the next week.

**Comment by ellen19967** [comment]
Many thanks! when will the code and dataset for collaborative tracking tasks be released?

**Comment by DerrickXuNu** [comment]
The dataset for detection/tracking/domain adaption is the same one, just the codebase api will change. I plan to release tracking sometime next week.
