### ISSUE TITLE
Qustion of Start

### ISSUE THREAD

**Issue by YuJiXYZ** [ucla-mobility/V2V4Real#10]
Hello, Dr. Xu, thank you for your outstanding work. I am currently retrying your code.

The problem I encountered is when visualizing the data sequence and displaying this error:'

![1687182249468](https://github.com/ucla-mobility/V2V4Real/assets/106587670/59bddf85-f8f1-4c24-920a-caad274c84c2)

I don't know what problem caused it, could you help me answer it?
Looking forward to your reply. Thank you very much~

**Comment by DerrickXuNu** [comment]
Thanks for using V2V4Real! It seems that you are installing a wrong spconv. What is the spconv version you are using?

**Comment by YuJiXYZ** [comment]
Oh, the spconv version is   spconv-cu113  2.3.6 .

**Comment by YuJiXYZ** [comment]
And I have tried the version of 2.3.3 and 2.3.5, the problem is also there.

**Comment by DerrickXuNu** [comment]
Can you try a bit lower version, like 2.0.0?

**Comment by YuJiXYZ** [comment]
OK, I have tried the version of 2.1.16 ( which is lowest version of matching), and the mistake is following:
![image](https://github.com/ucla-mobility/V2V4Real/assets/106587670/9f236ff1-f8d7-437b-9655-1dcc5455abfd)

**Comment by DerrickXuNu** [comment]
Are you able to run import spconv separately? I think there is something
wrong with your spconv installation

**Comment by YuJiXYZ** [comment]
Yes, I can not import spconv separately. (So I don't know how to slove it?)
And I have tried setup again, but the problem is always there. 
When I run "python opencood/utils/setup.py build_ext --inplace" command, I face the warning:
![image](https://github.com/ucla-mobility/V2V4Real/assets/106587670/90f4f03a-f48c-46ad-b055-d0c375cdd488)
And I run it again, the warning is disappear, so I'm not sure if this is the problem.

Thank you~

**Comment by DerrickXuNu** [comment]
> Yes, I can not import spconv separately. (So I don't know how to slove it?)
> 
> And I have tried setup again, but the problem is always there. 
> 
> When I run "python opencood/utils/setup.py build_ext --inplace" command, I face the warning:
> 
> ![image](https://github.com/ucla-mobility/V2V4Real/assets/106587670/90f4f03a-f48c-46ad-b055-d0c375cdd488)
> 
> And I run it again, the warning is disappear, so I'm not sure if this is the problem.
> 
> 
> 
> Thank you~

The "build_ext" is not the issue. There may be something wrong with your cuda version, please refer to spconv repo to resolve the issue.

**Comment by YuJiXYZ** [comment]
OK, I try it again. Thank you.

**Comment by eddyhkchiu** [comment]
Hi [YuJiXYZ](https://github.com/YuJiXYZ),

I am facing exact the same ImportError when running the starting visualization command.
Could you share how you solve this problem?

Thanks!

**Comment by DerrickXuNu** [comment]
Did you have a spconv cuda mismatch ? Previously, when I have my cuda in
Nvidia-driver as 11.6, but spconv with cuda11.3, this issue raised

**Comment by eddyhkchiu** [comment]
Hi Derrick,

Thanks for your reply.
From my nvidia-smi command, my nvidia-driver version is 
NVIDIA-SMI 465.19.01    
Driver Version: 465.19.01    
CUDA Version: 11.3

And my spconv version was 
spconv-cu113              2.3.6

I tried several different versions of spconv-cu113, and found 2.2.2 does not have this ImportError.
And my visualization command got another error related to Open3D display as follows, which seems to be a separate issue.

[Open3D WARNING] GLFW Error: GLX: Forward compatibility requested but GLX_ARB_create_context_profile is unavailable
[Open3D WARNING] Failed to create window
Traceback (most recent call last):
  File "opencood/visualization/vis_data_sequence.py", line 36, in <module>
    color_mode=opt.color_mode)
  File "/home/eddy/V2V4Real/opencood/visualization/vis_utils.py", line 683, in visualize_sequence_dataloader
    vis.get_render_option().background_color = [1.0, 1.0, 1.0]
AttributeError: 'NoneType' object has no attribute 'background_color'

Thanks!

**Comment by YuJiXYZ** [comment]
Hi, [eddyhkchiu](https://github.com/eddyhkchiu)

I find the problem before is my high vision of cuda. And I solve it.
I also encountered this issue during the visualization process. The Error is the same as you. I know it's the problem of Open3D. 
By the way, I encountered this issue when I train other repos of Dr. Xu, such as v2xvit. I have trying some solution before that don't work.
So I just train it now.

**Comment by WangzcBruce** [comment]
> Nvidia-driver 
![Uploading image.png…]()
I have faced the same question. my cuda version is 11.3 and spconv-cu113=2.3.6

**Comment by WangzcBruce** [comment]
> Hi Derrick,
> 
> Thanks for your reply. From my nvidia-smi command, my nvidia-driver version is NVIDIA-SMI 465.19.01 Driver Version: 465.19.01 CUDA Version: 11.3
> 
> And my spconv version was spconv-cu113 2.3.6
> 
> I tried several different versions of spconv-cu113, and found 2.2.2 does not have this ImportError. And my visualization command got another error related to Open3D display as follows, which seems to be a separate issue.
> 
> [Open3D WARNING] GLFW Error: GLX: Forward compatibility requested but GLX_ARB_create_context_profile is unavailable [Open3D WARNING] Failed to create window Traceback (most recent call last): File "opencood/visualization/vis_data_sequence.py", line 36, in color_mode=opt.color_mode) File "/home/eddy/V2V4Real/opencood/visualization/vis_utils.py", line 683, in visualize_sequence_dataloader vis.get_render_option().background_color = [1.0, 1.0, 1.0] AttributeError: 'NoneType' object has no attribute 'background_color'
> 
> Thanks!

Friend, have you fixed the nonetype error?
![image](https://github.com/ucla-mobility/V2V4Real/assets/45158420/70022280-a348-4427-a30b-043da010556a)

**Comment by YuJiXYZ** [comment]
I have not fixed yet either.
I think we still need to ask [DerrickXuNu](https://github.com/DerrickXuNu) for a solution to the problem. (●'◡'●)

**Comment by DerrickXuNu** [comment]
Hi Bruce,

Your issue is very easy to fix. You are giving a non-existing path. You
need to change the validate_dir in yaml to your local path.

**Comment by YuJiXYZ** [comment]
Hi, [DerrickXuNu](https://github.com/DerrickXuNu)
I have changed the validate_dir in yaml to my local path. But the mistake is following, what's the problem?
![image](https://github.com/ucla-mobility/V2V4Real/assets/106587670/27d2f102-40bc-4c55-887b-f93952757747)

**Comment by WangzcBruce** [comment]
Thank you a lot, Runsheng .Exactly, it lacks a visualization windows in the server of Ubuntu, leading to open3d creating windows error(Nonetype). I have installed xorg and started X11-forward of the linux server to fix the error.



----- Original Message -----

**Comment by DerrickXuNu** [comment]
> Hi, [DerrickXuNu](https://github.com/DerrickXuNu)
> 
> I have changed the validate_dir in yaml to my local path. But the mistake is following, what's the problem?
> 
> ![image](https://github.com/ucla-mobility/V2V4Real/assets/106587670/27d2f102-40bc-4c55-887b-f93952757747)
> 
> 

Are you running on a remote server?

**Comment by YuJiXYZ** [comment]
Yes, I have opened X11-forward and use the VcXsrv to forward my window. 
But I cann't get the visualization windows.
