### ISSUE TITLE
Tracking code release time?

### ISSUE THREAD

**Issue by eddyhkchiu** [ucla-mobility/V2V4Real#12]
Hello,

Thanks for the great work on this real v2v dataset and the code release!
I wonder when the tracking part of the code will be released?

Thanks!

**Comment by DerrickXuNu** [comment]
I am still cleaning code. But basically, I saved the detection results into .npy, and use this repo to perform tracking: https://github.com/xinshuoweng/AB3DMOT

**Comment by eddyhkchiu** [comment]
My third-party implementation of V2V4Real's CoBEVT + AB3DMOT is at https://github.com/eddyhkchiu/DMSTrack . The code also contains my recent ICRA2024 paper DMSTrack. More details can be seen in https://eddyhkchiu.github.io/dmstrack.github.io/ .
