### ISSUE TITLE
question of visiualzation

### ISSUE THREAD

**Issue by WangzcBruce** [ucla-mobility/V2V4Real#16]
![image](https://github.com/ucla-mobility/V2V4Real/assets/45158420/434f8707-76c7-4dd0-81e1-4b2a13b8bc82)
I have faced the same question of the mentioned in the https://github.com/ucla-mobility/V2V4Real/issues/10#issuecomment-1604965783  my cuda version is 11.3 and spconv-cu113=2.3.6

**Comment by WangzcBruce** [comment]
(v2v4real) root@4f6dc4328f28:~/V2V4Real# pip list
Package              Version   Editable project location
-------------------- --------- -------------------------
addict               2.4.0
ansi2html            1.8.0
attrs                23.1.0
backcall             0.2.0
bypy                 1.8.2
ccimport             0.4.2
certifi              2023.5.7
charset-normalizer   3.1.0
click                8.1.3
cmake                3.26.4
ConfigArgParse       1.5.3
cumm                 0.4.10
cumm-cu113           0.4.10
cycler               0.11.0
Cython               0.29.35
dash                 2.11.0
dash-core-components 2.0.0
dash-html-components 2.0.0
dash-table           5.0.0
debugpy              1.6.7
decorator            5.1.1
dill                 0.3.6
easydict             1.10
einops               0.6.1
entrypoints          0.4
fastjsonschema       2.17.1
filelock             3.12.2
fire                 0.5.0
Flask                2.2.5
fsspec               2023.1.0
huggingface-hub      0.15.1
idna                 3.4
imageio              2.31.1
importlib-metadata   6.7.0
importlib-resources  5.12.0
ipykernel            6.16.2
ipython              7.34.0
ipywidgets           8.0.6
itsdangerous         2.1.2
jedi                 0.18.2
Jinja2               3.1.2
joblib               1.2.0
jsonschema           4.17.3
jupyter_client       7.4.9
jupyter_core         4.12.0
jupyterlab-widgets   3.0.7
kiwisolver           1.4.4
lark                 1.1.5
llvmlite             0.32.1
MarkupSafe           2.1.3
matplotlib           3.3.4
matplotlib-inline    0.1.6
mkl-fft              1.1.0
mkl-random           1.1.0
mkl-service          2.3.0
multiprocess         0.70.14
nbformat             5.7.0
nest-asyncio         1.5.6
networkx             2.6.3
ninja                1.11.1
numba                0.49.0
numpy                1.21.6
open3d               0.17.0
opencv-python        4.5.1.48
packaging            23.1
pandas               1.3.5
parso                0.8.3
pccm                 0.4.7
pexpect              4.8.0
pickleshare          0.7.5
Pillow               9.5.0
pip                  23.1.2
pkgutil_resolve_name 1.3.10
plotly               5.15.0
portalocker          2.7.0
prompt-toolkit       3.0.38
protobuf             4.23.3
psutil               5.9.5
ptyprocess           0.7.0
pybind11             2.10.4
Pygments             2.15.1
pyparsing            3.1.0
pyquaternion         0.9.9
pyrsistent           0.19.3
PySocks              1.7.1
python-dateutil      2.8.2
pytz                 2023.3
PyWavelets           1.3.0
PyYAML               6.0
pyzmq                25.1.0
requests             2.31.0
requests-toolbelt    1.0.0
retrying             1.3.4
safetensors          0.3.1
scikit-image         0.19.3
scikit-learn         1.0.2
scipy                1.5.4
setuptools           68.0.0
shapely              2.0.0
six                  1.16.0
spconv-cu113         2.3.6
tenacity             8.2.2
tensorboardX         2.6.1
termcolor            2.3.0
threadpoolctl        3.1.0
tifffile             2021.11.2
timm                 0.9.2
torch                1.12.0
torchvision          0.13.0
tornado              6.2
tqdm                 4.65.0
traitlets            5.9.0
typing_extensions    4.6.3
urllib3              2.0.3
V2V4Real             0.1.0     /root/V2V4Real
wcwidth              0.2.6
Werkzeug             2.2.3
wheel                0.40.0
widgetsnbextension   4.0.7
zipp                 3.15.0

**Comment by eddyhkchiu** [comment]
I use spconv-cu113=2.2.2 to solve this problem.

**Comment by DerrickXuNu** [comment]
Did you solve the issue?
