### ISSUE TITLE
question about the data split

### ISSUE THREAD

**Issue by jinsuyoo** [ucla-mobility/V2V4Real#21]
I would first like to thank you and your team for the great work!

While exploring the dataset, I found trainset and testset both include a clip named "testoutput_CAV_data_2022-03-15-09-54-40_0".

I just wanted to ask if this would be an issue or ok. (I downloaded the data from US + Google Drive)

Thanks in advance!!

**Comment by DerrickXuNu** [comment]
Thanks for using V2V4Real. That was a careless mistake that puts a slice of data in both the training and testing sets. You could remove it from the training set or keep it to make the comparison with the benchmark result consistent.
