### ISSUE TITLE
Question about the V2V4Real dataset

### ISSUE THREAD

**Issue by CSwakeQAQ** [ucla-mobility/V2V4Real#5]
Thank u for such great contribution!
I have downloaded the V2V4Real dataset from the official website, but after I unpacked it, I found that some parameters in the yaml file did not display properly.I tried to load these yaml files as dict, but failed.I wondered whether I had chosen the wrong encoding method?Or is the dataset yaml file encrypted?
`ego_speed: 0
gps:
- !!python/object/apply:numpy.core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    dIGJR/v8Q0A=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    jh8Jfy/BVMA=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    5QmEnWKQbEA=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    HQQY9LDgAkA=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    1bgF4CXuab8=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    29r2H6qipL8=
lidar_pose: &id002 !!python/object/apply:numpy.core.multiarray._reconstruct
  args:
  - !!python/name:numpy.ndarray ''
  - !!python/tuple
    - 0
  - !!binary |
    Yg==
  state: !!python/tuple
  - 1
  - !!python/tuple
    - 4
    - 4
  - *id001
  - false
  - !!binary |
    Tnrf+Nqz5b96jzNN2H7nv8mrcwzIXp+/TDeJQWBohcAQ7PgvEITnP+pA1lOrr+W/C0hW2dL+mr/y
    0k1iEGxpQAJ1Vk0IBFe/+pQI+UWupL9tA3egTvnvP4eiQJ/IExxAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAA8D8=
true_ego_pos: *id002
vehicles:
  7:
    angle:
    - 0.0
    - 27.056938836177025
    - 0.0
    ass_id: -1
    center:
    - 0
    - 0
    - 0
    extent:
    - 2.0354528287399662
    - 1.0361092723488456
    - 0.8501376623636069
    location:
    - 53.36773910970518
    - 12.212414634296548
    - -1.45655303837862
    obj_type: Car
`

**Comment by DerrickXuNu** [comment]
Hi, I used pyyaml to save the annotation. When you use the pyyaml to save numpy array, it will show things like this. Please check opencood.hypes_yaml.yaml_utill.load_yaml to see how to load the annotation properlt
