### ISSUE TITLE
Issue for V2VNet venue 

### ISSUE THREAD

**Issue by wangjksjtu** [ucla-mobility/V2V4Real#9]
Thanks for the amazing work! Could you help correct this minor issue in the README.md? V2VNet is ECCV2020 instead of ECCV2022. Thanks ;)

![image](https://github.com/ucla-mobility/V2V4Real/assets/22170175/7d4589fc-79e4-4b61-af29-f56a7aff78b7)

**Comment by DerrickXuNu** [comment]
Hi Jingkang, thanks for pointing out the mistake! I have modified it.

**Comment by wangjksjtu** [comment]
thanks!
